import Head from "next/head";

import { gql } from "@apollo/client";
import client from "../apollo-client";

import { MenuBar } from "../components/MenuBar";

export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>Malluchan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MenuBar />
      <h1 className="text-3xl font-bold underline">Home Page</h1>
      {/* console.log(posts); */}
    </div>
  );
}

export async function getServerSideProps() {
  try {
    const { data, loading } = await client.query({
      query: gql`
        query getPosts {
          body
        }
      `,
    });
    console.log(data);
    return {
      props: {
        posts: data,
        loading: loading,
      },
    };
  } catch (e) {
    console.log(e.networkError.result.errors);
  }
}
