import Head from "next/head";

import { MenuBar } from "../components/MenuBar";

// import { PostCard } from "../components/PostCard";
import PostCard from "../components/PostCard";

import { useQuery } from "urql";
import { client, ssrCache } from "../urqlClient";

const POST_QUERY = `
query {
  getPosts{
  username
  body
  id
  likes{
    username
  }
  likeCount
  commentCount
  createdAt
  photo
  }
}
`;
export default function Home() {
  const [result] = useQuery({
    query: POST_QUERY,
  });

  const { data, fetching, error } = result;

  if (fetching) return "loading";
  if (error) {
    console.log(error);
  }
  return (
    <>
      <Head>
        <title>Malluchan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MenuBar />
      {data.getPosts &&
        data.getPosts.map((post) => {
          return (
            <>
              <PostCard posts={post} loading={fetching} />
            </>
          );
        })}
    </>
  );
}

// export async function getServerSideProps() {
//   await client.query(POST_QUERY).toPromise();
//   return {
//     props: {
//       urqlState: ssrCache.extractData(),
//     },
//   };
// }
