import Head from "next/head";

import { gql } from "@apollo/client";
import client from "../apollo-client";

import { MenuBar } from "../components/MenuBar";

import { PostCard } from "../components/PostCard";

export default function Home({ posts, loading }) {
  return (
    <>
      <Head>
        <title>Malluchan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MenuBar />
      <PostCard posts={posts} loading={loading} />
    </>
    // </div>
  );
}

export async function getServerSideProps() {
  const {
    data: { getPosts: posts },
    loading,
  } = await client.query({
    query: gql`
      query {
        getPosts {
          username
          body
          id
          likeCount
          commentCount
          createdAt
        }
      }
    `,
  });
  return {
    props: {
      posts,
      loading: loading,
    },
  };
}
